// gstack specialists — each one becomes a voice bot that can join a meeting.
// name = slash-command id, role = persona, desc = one-liner, icon = emoji, accent = hex.
window.SPECIALISTS = [
  {
    id: "office-hours",
    name: "Office Hours",
    role: "YC Office Hours",
    desc: "Ruthless product interrogation in the YC style.",
    icon: "YC",
    glyph: "◉",
    accent: "#ff6b2b",
    category: "Strategy",
  },
  {
    id: "plan-ceo-review",
    name: "CEO Review",
    role: "CEO / Founder",
    desc: "Strategic rethink: is this the right bet, right now?",
    icon: "♛",
    glyph: "♛",
    accent: "#ffb020",
    category: "Strategy",
  },
  {
    id: "plan-eng-review",
    name: "Eng Review",
    role: "Engineering Manager",
    desc: "Architecture lock-in before a single line is written.",
    icon: "⎇",
    glyph: "⎇",
    accent: "#5ee1b5",
    category: "Planning",
  },
  {
    id: "plan-design-review",
    name: "Design Plan",
    role: "Senior Designer",
    desc: "Design rubric against a gold-standard product.",
    icon: "◈",
    glyph: "◈",
    accent: "#d68cff",
    category: "Planning",
  },
  {
    id: "plan-devex-review",
    name: "DX Plan",
    role: "DX Lead",
    desc: "Developer experience plan: friction, first-run, docs.",
    icon: "❮❯",
    glyph: "❮❯",
    accent: "#7dd3fc",
    category: "Planning",
  },
  {
    id: "design-consultation",
    name: "Design Consult",
    role: "Design Partner",
    desc: "Design system direction & product surface review.",
    icon: "✦",
    glyph: "✦",
    accent: "#f0abfc",
    category: "Design",
  },
  {
    id: "design-shotgun",
    name: "Design Shotgun",
    role: "Design Explorer",
    desc: "Generates six mockup variants in parallel.",
    icon: "⁂",
    glyph: "⁂",
    accent: "#fb7185",
    category: "Design",
  },
  {
    id: "design-html",
    name: "Design HTML",
    role: "Design Engineer",
    desc: "Hand-coded, production-grade HTML from a spec.",
    icon: "</>",
    glyph: "</>",
    accent: "#a78bfa",
    category: "Design",
  },
  {
    id: "review",
    name: "Code Review",
    role: "Staff Engineer",
    desc: "Reads every line. Catches what you missed.",
    icon: "⌘",
    glyph: "⌘",
    accent: "#00e5ff",
    category: "Engineering",
  },
  {
    id: "investigate",
    name: "Investigate",
    role: "Debugger",
    desc: "Root-cause analysis. Hypothesis → evidence → fix.",
    icon: "⌕",
    glyph: "⌕",
    accent: "#fde047",
    category: "Engineering",
  },
  {
    id: "design-review",
    name: "Design Audit",
    role: "Designer Who Codes",
    desc: "Live UI audit against the design rubric.",
    icon: "◐",
    glyph: "◐",
    accent: "#f472b6",
    category: "Review",
  },
  {
    id: "devex-review",
    name: "DX Audit",
    role: "DX Tester",
    desc: "Live developer-experience audit: clone → run → feel.",
    icon: "▤",
    glyph: "▤",
    accent: "#60a5fa",
    category: "Review",
  },
  {
    id: "qa",
    name: "QA",
    role: "QA Lead",
    desc: "Writes tests, runs them, fixes what breaks.",
    icon: "✓",
    glyph: "✓",
    accent: "#4ade80",
    category: "Quality",
  },
  {
    id: "cso",
    name: "CSO",
    role: "Chief Security Officer",
    desc: "OWASP + STRIDE threat model on every change.",
    icon: "⛨",
    glyph: "⛨",
    accent: "#f87171",
    category: "Quality",
  },
  {
    id: "ship",
    name: "Ship",
    role: "Release Engineer",
    desc: "Opens the PR with the right description & reviewers.",
    icon: "▲",
    glyph: "▲",
    accent: "#34d399",
    category: "Release",
  },
  {
    id: "land-and-deploy",
    name: "Land & Deploy",
    role: "Release Engineer",
    desc: "Merges, deploys, verifies the new bits are live.",
    icon: "⇧",
    glyph: "⇧",
    accent: "#22d3ee",
    category: "Release",
  },
  {
    id: "canary",
    name: "Canary",
    role: "SRE",
    desc: "Watches logs & metrics after deploy. Rolls back fast.",
    icon: "☀",
    glyph: "☀",
    accent: "#fbbf24",
    category: "Release",
  },
  {
    id: "retro",
    name: "Retro",
    role: "Engineering Manager",
    desc: "Weekly retrospective: what shipped, what slipped.",
    icon: "↻",
    glyph: "↻",
    accent: "#c4b5fd",
    category: "Ops",
  },
];

// Team presets — curated groupings for one-click multi-select.
// Clicking a team pill ADDS its members to the current selection (additive, not a toggle).
window.TEAMS = [
  {
    id: "founding",
    name: "Founding Team",
    specialists: ["office-hours", "plan-ceo-review", "plan-eng-review"],
  },
  {
    id: "design",
    name: "Design Team",
    specialists: [
      "plan-design-review",
      "design-consultation",
      "design-shotgun",
      "design-html",
      "design-review",
    ],
  },
  {
    id: "build-review",
    name: "Build & Review",
    specialists: ["plan-eng-review", "review", "investigate"],
  },
  {
    id: "qa-ship",
    name: "QA & Ship",
    specialists: ["qa", "cso", "ship", "land-and-deploy", "canary"],
  },
  {
    id: "dx",
    name: "DX Team",
    specialists: ["plan-devex-review", "devex-review"],
  },
  {
    id: "retro",
    name: "Retro",
    specialists: ["retro"],
  },
];
