-- Phase 3: live transcript, post-call artifact, dispatch queue.
--
-- summary        markdown call-notes generated by the brain after the call
-- dispatched_at  when the assignment actually reached a worker. For queued
--                dispatches this is later than created_at; billable time
--                counts from here, not from when the user clicked.
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ;
